# Generated by Django 5.1.6 on 2025-05-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0008_alter_notificacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='presentacion',
            field=models.CharField(max_length=100),
        ),
    ]
